{{- if .Values.server.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.server.service.nameOverride }}
  name: {{ .Values.server.service.nameOverride | quote }}
  {{- else }}
  name: {{ include "server.name" . | quote }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- include "server.annotations" . | nindent 4 }}
    {{- include "quote.object" .Values.server.service.annotations | indent 4 }}
spec:
  type: {{ .Values.server.service.type | quote }}
  selector:
    {{- include "server.selector" . | nindent 4 }}
  ports:
    {{- range .Values.server.service.ports }}
    - name: {{ .name }}
      port: {{ .ports.external }}
      targetPort: {{ .ports.internal }}
      protocol: {{ .protocol }}
    {{- end }}
{{- end }}
