apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.name" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- include "server.annotations" . | nindent 4 }}
type: Opaque
stringData:
  SOME_SECRET_HERE: {{ .Chart.Name | quote }}
