apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.name" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.server.tracing.jaeger.enabled }}
    sidecar.jaegertracing.io/inject: "true"
    {{- end }}
    {{- include "server.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "server.selector" . | nindent 6 }}
  replicas: {{ .Values.server.autoscaling.replicas.min }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        {{- include "server.labels" . | nindent 8 }}
      annotations:
        {{- include "server.annotations" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- if .Values.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
      {{- end }}
      containers:
        - name: server
          image: {{ .Values.server.image | quote }}
          imagePullPolicy: {{ .Values.pullPolicy | quote }}
          resources: {{- toYaml .Values.server.resources | nindent 14 }}
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.server.valuesFrom.env.secret }}
            {{- range .Values.server.valuesFrom.env.secret }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .key }}
                  name: {{ .secretName }}
            {{- end }}
            {{- end }}
            {{- if .Values.server.valuesFrom.env.configmap }}
            {{- range .Values.server.valuesFrom.env.configmap }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  key: {{ .key }}
                  name: {{ .configMapName }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "server.name" . | quote }}
            - secretRef:
                name: {{ include "server.name" . | quote }}
            {{- if .Values.server.valuesFrom.envFrom.configMapRef }}
            {{- range .Values.server.valuesFrom.envFrom.configMapRef }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if .Values.server.valuesFrom.envFrom.secretRef }}
            {{- range .Values.server.valuesFrom.envFrom.secretRef }}
              - secretRef:
                  name: {{ . }}
            {{- end }}
            {{- end }}
          ports:
          {{- range .Values.server.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .ports.internal }}
              protocol: {{ .protocol }}
          {{- end }}
          {{- if .Values.server.probes.readiness }}
          readinessProbe: {{- toYaml .Values.server.probes.readiness | nindent 12 }}
          {{- end }}
          {{- if .Values.server.probes.liveness }}
          livenessProbe: {{- toYaml .Values.server.probes.liveness | nindent 12 }}
          {{- end }}
        {{- if .Values.server.tracing.jaeger.enabled }}
        - name: jaeger-agent
          image: {{ .Values.jaeger.agent.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          resources: {{- toYaml .Values.server.tracing.jaeger.resources | nindent 14 }}
          ports:
            - containerPort: 5775
              name: zk-compact-trft
              protocol: UDP
            - containerPort: 5778
              name: config-rest
              protocol: TCP
            - containerPort: 6831
              name: jg-compact-trft
              protocol: UDP
            - containerPort: 6832
              name: jg-binary-trft
              protocol: UDP
            - containerPort: 14271
              name: admin-http
              protocol: TCP
          args:
            - --reporter.grpc.host-port={{ .Values.jaeger.collector.endpoint }}
            - --reporter.type=grpc
        {{- end }}

      {{- if .Values.server.nodeSelector }}
      nodeSelector: {{ toYaml .Values.server.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .Values.server.affinity }}
      affinity: {{ toYaml .Values.server.affinity | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ include "server.name" . | quote }}
                topologyKey: kubernetes.io/hostname
      {{- end }}

      {{- if .Values.server.tolerations }}
      tolerations: {{ toYaml .Values.server.tolerations | nindent 8 }}
      {{- end }}
