apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.name" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- include "server.annotations" . | nindent 4 }}
data:
  TITLE: {{ .Values.server.config.title | quote }}
  MESSAGE: {{ .Values.server.config.message | quote }}
  PARAMS: {{ .Values.server.config.param | quote }}
  ALLOWED_URL_PATTERNS: {{ .Values.server.config.allowedPatterns | join "," | quote }}
