apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.name" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- include "server.annotations" . | nindent 4 }}
data:
  APP_NAME: {{ .Chart.Name | quote }}
